openapi: 3.0.0

info:
  title: Object detection API
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/{basePath}
    description: Development API server
    variables:
      basePath:
        default: v1

paths:
  /token/registration:
    post:
      tags:
        - Authentication
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
  /token/refresh:
    post:
      tags:
        - Authentication
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
  /users:
    get:
      tags:
        - User
      security:
        - bearerAuth: []
      produces:
        - application/json
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'




    post:
      tags:
        - User
      security:
        - bearerAuth: []
  /users/{id}:
    get:
      tags:
        - User
      security:
        - bearerAuth: []
    put:
      tags:
        - User
      security:
        - bearerAuth: []
    delete:
      tags:
        - User
      security:
        - bearerAuth: []
  /users/whoami:
    get:
      tags:
        - User
      security:
        - bearerAuth: []
      produces:
        - application/json
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  schemas:
    UserRequest:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          description: user name
          example: Alex
        email:
          type: string
          description: user email
          example: alex@example.com
        password:
          type: string
          description: user password
          example: Pa$$w0rd!
    TokenResponse:
      type: object
      properties:
        name:
          type: string
          description: name
          example: Alex
        email:
          type: string
          description: email
          example: alex@example.com
        token:
          type: string
          description: bearer token
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyIwIjoiMzZiYzZhMDMtMDY4NS00MGVjLWI1ODMtZGY4OWY1NDU2NDU1In0.BEyBhM1lFEzUhvm4VJNS3QHdymgsu35I94eApqH1XrM
    Role:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: role id
          example: 2
        name:
          type: string
          description: role name
          example: ROLE_USER
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: user id
          example: 1
        name:
          type: string
          description: user name
          example: Alex
        email:
          type: string
          description: user email
          example: alex@example.com
        lastLoginIP:
          type: string
          description: user last login ip
          example: 127.0.0.1
        lastLoginAt:
          type: string
          format: date-time
          description: user last login at
          example: 2023-11-19T04:21:43
        createdAt:
          type: string
          format: date-time
          description: user last login at
          example: 2021-09-17T02:19:41
        updatedAt:
          type: string
          format: date-time
          description: user last login at
          example: 2022-10-18T03:20:42
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
    Users:
      type: array
      items:
        $ref: '#/components/schemas/User'

  parameters:
    # ---
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                # example: 'Access token is missing or invalid'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                # example: 'Access token is missing or invalid'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                # example: 'Access token is missing or invalid'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                # example: 'Access token is missing or invalid'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
